##TRIGGERS
-- Crear trigger para actualizar el monto total en la tabla PEDIDOS
DELIMITER //
CREATE TRIGGER ActualizarMontoTotalPedido
AFTER INSERT ON CARTAS_POR_PEDIDO
FOR EACH ROW
BEGIN
    DECLARE total_monto DECIMAL(9, 2);
    
    SELECT SUM(CARTAS.PRICE * NEW.QUANTITY) INTO total_monto
    FROM CARTAS_POR_PEDIDO
    JOIN CARTAS ON CARTAS_POR_PEDIDO.ID_CARTA = CARTAS.ID_CARTA
    WHERE CARTAS_POR_PEDIDO.ID_PEDIDO = NEW.ID_PEDIDO;
    
    UPDATE PEDIDOS
    SET MONTO = total_monto
    WHERE ID_PEDIDO = NEW.ID_PEDIDO;
END;
//
DELIMITER ;

-- Crear trigger para actualizar el monto total en la tabla ENVIOS
DELIMITER //
CREATE TRIGGER ActualizarMontoTotalEnvio
AFTER INSERT ON CARTAS_POR_PEDIDO
FOR EACH ROW
BEGIN
    DECLARE total_monto DECIMAL(9, 2);
    
    SELECT SUM(CARTAS.PRICE * NEW.QUANTITY) INTO total_monto
    FROM CARTAS_POR_PEDIDO
    JOIN CARTAS ON CARTAS_POR_PEDIDO.ID_CARTA = CARTAS.ID_CARTA
    WHERE CARTAS_POR_PEDIDO.ID_PEDIDO = NEW.ID_PEDIDO;
    
    UPDATE ENVIOS
    SET MONTO = total_monto
    WHERE ID_PEDIDO = NEW.ID_PEDIDO;
END;
//
DELIMITER ;
